BulkyWeb/Areas/Admin/Controllers/OrderController.cs
using Bulky.DataAccess.Repository;
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Models.ViewModels;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using System.Globalization;
using System.Security.Claims;

namespace BulkyWeb.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize]
public class OrderController : Controller
{
	private readonly IUnitOfWork _unitOfWork;
	[BindProperty]
	public OrderVM OrderVM { get; set; }
	public OrderController(IUnitOfWork unitOfWork)
	{
		_unitOfWork = unitOfWork;
	}

	public IActionResult Index()
	{
		return View();
	}

	[HttpPost]
	public IActionResult CultureManagement(string culture, string returnUrl)
	{
		Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
			CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
			new CookieOptions { Expires = DateTimeOffset.Now.AddDays(30) });

		return LocalRedirect(returnUrl);
	}

	private string GetCurrentCulture()
	{
		return CultureInfo.CurrentCulture.Name;
	}

	public IActionResult Details(int orderId)
	{
		 OrderVM =  new ()
		{
			OrderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderId, includeProperties: "ApplicationUser"),
			OrderDetail = _unitOfWork.OrderDetail.GetAll(u => u.OrderHeaderId == orderId, includeProperties: "Product")
		};

		return View(OrderVM);
	}

	[HttpPost]
	[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
	public IActionResult UpdateOrderDetail()
	{
		var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);

		orderHeaderFromDb.Name = OrderVM.OrderHeader.Name;
		orderHeaderFromDb.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
		orderHeaderFromDb.StreetAddress = OrderVM.OrderHeader.StreetAddress;
		orderHeaderFromDb.City = OrderVM.OrderHeader.City;
		orderHeaderFromDb.State = OrderVM.OrderHeader.State;
		orderHeaderFromDb.PostalCode = OrderVM.OrderHeader.PostalCode;

		if (!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier))
		{
			orderHeaderFromDb.Carrier= OrderVM.OrderHeader.Carrier;
		}

        if (!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
        {
            orderHeaderFromDb.Carrier = OrderVM.OrderHeader.Carrier;
        }

		_unitOfWork.OrderHeader.Update(orderHeaderFromDb);
		_unitOfWork.Save();

		TempData["Success"] = GetCurrentCulture()=="en" ? "Order Details Updated Successfully." : "Сведения о Заказе Успешно Обновлены.";

        return RedirectToAction(nameof(Details), new {orderId=orderHeaderFromDb.Id});
    }

	[HttpPost]
	[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
	public IActionResult StartProcessing()
	{
		_unitOfWork.OrderHeader.UpdateStatus(OrderVM.OrderHeader.Id, SD.StatusInProcessEN, SD.StatusInProcessRU);
		_unitOfWork.Save();

		TempData["Success"] = GetCurrentCulture() == "en" ?  "Order Status Updated Successfully." : "Статус Заказа Успешно Обновлен.";
		return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });

	}

	[HttpPost]
	[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
	public IActionResult ShipOrder()
	{
		var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
		orderHeaderFromDb.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
		orderHeaderFromDb.Carrier = OrderVM.OrderHeader.Carrier;
		orderHeaderFromDb.OrderStatusEN =SD.StatusShippedEN;
		orderHeaderFromDb.OrderStatusRU =SD.StatusShippedRU;
		orderHeaderFromDb.ShippingDate = DateTime.Now;

		if (orderHeaderFromDb.PaymentStatusEN==SD.PaymentStatusDelayedPaymentEN)
		{
			orderHeaderFromDb.PaymentDueDate = DateOnly.FromDateTime(DateTime.Now.AddDays(30));
		}

		_unitOfWork.OrderHeader.Update(orderHeaderFromDb);
		_unitOfWork.Save();


		TempData["Success"] = GetCurrentCulture() == "en" ? "Order Shipped  Successfully." : "Заказ Успешно Отправлен.";
		return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });

	}


	[HttpPost]
	[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
	public IActionResult CancelOrder()
	{
		var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);

		if(orderHeaderFromDb.PaymentStatusEN==SD.PaymentStatusApprovedEN)
		{
			var options = new RefundCreateOptions()
			{
				Reason = RefundReasons.RequestedByCustomer,
				PaymentIntent = orderHeaderFromDb.PaymentIntentId,
			};

			var service = new RefundService();
			Refund refund = service.Create(options);
			_unitOfWork.OrderHeader.UpdateStatus(orderHeaderFromDb.Id, SD.StatusCancelledEN, SD.StatusCancelledRU, SD.StatusRefundedEN, SD.StatusRefundedRU);
		}

		else
		{
			_unitOfWork.OrderHeader.UpdateStatus(orderHeaderFromDb.Id, SD.StatusCancelledEN, SD.StatusCancelledRU, SD.StatusCancelledEN, SD.StatusCancelledRU);
		}

		
		_unitOfWork.Save();
		TempData["Success"] = GetCurrentCulture() == "en" ? "Order Canceled Successfully.": "Заказ Успешно Отменен.";
		return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });

	}

	[ActionName("Details")]
	[HttpPost]
	public IActionResult Details_PAY_NOW()
	{
		OrderVM.OrderHeader = _unitOfWork.OrderHeader
				.Get(u => u.Id == OrderVM.OrderHeader.Id, includeProperties: "ApplicationUser");
		OrderVM.OrderDetail = _unitOfWork.OrderDetail
			.GetAll(u => u.OrderHeaderId == OrderVM.OrderHeader.Id, includeProperties: "Product");

        //stripe logic
        var domain = Request.Scheme + "://" + Request.Host.Value + "/";
        var options = new Stripe.Checkout.SessionCreateOptions
		{
			SuccessUrl = domain + $"admin/order/PaymentConfirmation?orderHeaderId={OrderVM.OrderHeader.Id}",
			CancelUrl = domain + $"admin/order/details?orderId={OrderVM.OrderHeader.Id}",
			LineItems = new List<Stripe.Checkout.SessionLineItemOptions>(),
			Mode = "payment",
		};

		foreach (var item in OrderVM.OrderDetail)
		{
			var sessionLineItem = new SessionLineItemOptions
			{
				PriceData = new SessionLineItemPriceDataOptions
				{
					UnitAmount = (long)(item.Price * 100),
					Currency = "usd",
					ProductData = new SessionLineItemPriceDataProductDataOptions
					{
						Name = GetCurrentCulture()=="en"  ? item.Product.TitleEN : item.Product.TitleRU
					}
				},
				Quantity = item.Count
			};
			options.LineItems.Add(sessionLineItem);
		}

		var service = new Stripe.Checkout.SessionService();
		Session session = service.Create(options);
		_unitOfWork.OrderHeader.UpdateStripePaymentID(OrderVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
		_unitOfWork.Save();
		Response.Headers.Add("Location", session.Url);
		return new StatusCodeResult(303);
	}


	public IActionResult PaymentConfirmation(int orderHeaderId)
	{
		OrderHeader orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderHeaderId, includeProperties: "ApplicationUser");
		if (orderHeader.PaymentStatusEN == SD.PaymentStatusDelayedPaymentEN)
		{
			//this is an order by company

			var service = new SessionService();

			Session session = service.Get(orderHeader.SessionId);

			if (session.PaymentStatus.ToLower() == "paid")
			{
				_unitOfWork.OrderHeader.UpdateStripePaymentID(orderHeaderId, session.Id, session.PaymentIntentId);
				_unitOfWork.OrderHeader.UpdateStatus(orderHeaderId, orderHeader.OrderStatusEN, orderHeader.OrderStatusRU,  SD.PaymentStatusApprovedEN, SD.PaymentStatusApprovedRU);
				_unitOfWork.Save();
			}
		}

		return View(orderHeaderId);
	}



	#region API CALLS

	[HttpGet]
	public IActionResult GetAll(string status)
	{

		IEnumerable<OrderHeader> objOrderHeaders;

		if(User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
		{
			objOrderHeaders = _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser").ToList();
        }
		else
		{
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

			objOrderHeaders = _unitOfWork.OrderHeader
				.GetAll(u => u.ApplicationUserId == userId, includeProperties: "ApplicationUser");

        }


		switch (status)
		{
			case "paymentpending":
					objOrderHeaders = objOrderHeaders.Where(u=>u.PaymentStatusEN==SD.PaymentStatusDelayedPaymentEN);
				break;
			case "inprocess":
				objOrderHeaders = objOrderHeaders.Where(u => u.OrderStatusEN == SD.StatusInProcessEN);
				break;
			case "completed":
				objOrderHeaders = objOrderHeaders.Where(u => u.OrderStatusEN == SD.StatusShippedEN);
				break;
			case "approved":
				objOrderHeaders = objOrderHeaders.Where(u => u.OrderStatusEN == SD.StatusApprovedEN);
				break;
			default:
				break;
		}
		return Json(new { data = objOrderHeaders });
	}

	#endregion

}

BulkyWeb/Areas/Admin/Controllers/UserController.cs
using Bulky.DataAccess.Data;
using Bulky.DataAccess.Repository;
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Models.ViewModels;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace BulkyWeb.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class UserController : Controller
{
	private readonly IUnitOfWork _unitOfWork;

	private readonly RoleManager<IdentityRole> _roleManager;
	private readonly UserManager<IdentityUser> _userManager;

	public UserController(IUnitOfWork unitOfWork, RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
	{
		_unitOfWork = unitOfWork;
		_roleManager = roleManager;
		_userManager = userManager;
	}

	public IActionResult Index()
	{
		return View();
	}

	[HttpPost]
	public IActionResult CultureManagement(string culture, string returnUrl)
	{
		Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
			CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
			new CookieOptions { Expires = DateTimeOffset.Now.AddDays(30) });

		return LocalRedirect(returnUrl);
	}

	private string GetCurrentCulture()
	{
		return CultureInfo.CurrentCulture.Name;
	}


	public IActionResult RoleManagement(string id)
	{
		RoleManagementVM roleVM = new()
		{
			ApplicationUser = _unitOfWork.ApplicationUser.Get(u=>u.Id==id, includeProperties: "Company"),

			RoleList = _roleManager.Roles.Select(u => new SelectListItem
			{
				Text = u.Name,
				Value = u.Name
			}),

			CompanyList = _unitOfWork.Company.GetAll().Select(u => new SelectListItem
			{
				Text = u.Name,
				Value = u.Id.ToString()
			}),
		};

		roleVM.ApplicationUser.Role = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u => u.Id == id))
			.GetAwaiter().GetResult().FirstOrDefault();


		return View(roleVM);
	}

	[HttpPost]
	public IActionResult RoleManagement(RoleManagementVM RoleVM)
	{
		string oldRole = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u => u.Id == RoleVM.ApplicationUser.Id))
			.GetAwaiter().GetResult().FirstOrDefault();


			ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == RoleVM.ApplicationUser.Id);

		if (!(RoleVM.ApplicationUser.Role == oldRole))
		{
			// a role was updated
			if(RoleVM.ApplicationUser.Role==SD.Role_Company)
			{
				applicationUser.CompanyId = RoleVM.ApplicationUser.CompanyId;
			}
			if(oldRole==SD.Role_Company)
			{
				applicationUser.CompanyId = null;
			}
			_unitOfWork.ApplicationUser.Update(applicationUser);
			_unitOfWork.Save();

			_userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
			_userManager.AddToRoleAsync(applicationUser, RoleVM.ApplicationUser.Role).GetAwaiter().GetResult();
		}

		else
		{
			if(oldRole==SD.Role_Company && applicationUser.CompanyId != RoleVM.ApplicationUser.CompanyId)
			{
				applicationUser.CompanyId = RoleVM.ApplicationUser.CompanyId;
				_unitOfWork.ApplicationUser.Update(applicationUser);
				_unitOfWork.Save();
			}
		}

		return RedirectToAction("Index");
	}

	[HttpPost]
	public IActionResult LockUnlock([FromBody] string id)
	{
		var objFromDb = _unitOfWork.ApplicationUser.Get(u => u.Id == id);

		if (objFromDb == null)
		{
			return Json(new { success = false, message = GetCurrentCulture()=="en" ? "Error while Locking/Unlocking" : "Ошибка при блокировке/разблокировке" });

		}

		if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
		{
			//user is currently locked and we need to unlock them
			objFromDb.LockoutEnd = DateTime.Now;
		}

		else
		{
			objFromDb.LockoutEnd = DateTime.Now.AddYears(100);
		}

		_unitOfWork.ApplicationUser.Update(objFromDb);
		_unitOfWork.Save();

		return Json(new { success = true, message = GetCurrentCulture() == "en" ? "Operation Successful" : "Операция прошла успешно" });
	}



	#region API CALLS

	[HttpGet]
	public IActionResult GetAll()
	{
		List<ApplicationUser> objUserList = _unitOfWork.ApplicationUser.GetAll(includeProperties: "Company").ToList();

		foreach (var user in objUserList)
		{
			user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();

			if (user.Company == null)
			{
				user.Company = new() { Name = "" };
			}
		}

		return Json(new { data = objUserList });
	}

	#endregion

}

BulkyWeb/ViewComponents/ShoppingCartViewComponent.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyWeb.ViewComponents;

public class ShoppingCartViewComponent : ViewComponent
{
    public readonly IUnitOfWork _unitOfWork;

    public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

        if (claim != null)
        {
            if (HttpContext.Session.GetInt32(SD.SessionCart) == null)
            {
                HttpContext.Session.SetInt32(SD.SessionCart,
             _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).Count());
            }
            return View(HttpContext.Session.GetInt32(SD.SessionCart));
        }
        else
        {
            HttpContext.Session.Clear();
            return View(0);
        }
    }
}

BulkyWeb/Views/Shared/_Culture.cshtml
@using Microsoft.AspNetCore.Localization
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@inject Microsoft.Extensions.Options.IOptions<RequestLocalizationOptions> locOptions

@{
	var culture = Context.Features.Get<IRequestCultureFeature>();
	var cultureList = locOptions.Value.SupportedUICultures.Select(
		x => new SelectListItem { Value = x.Name, Text = localizer.GetString(x.Name) }).ToList();
	var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" 
	: $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}


	<div>
	<form  asp-action="CultureManagement" method="post"
		  asp-route-returnUrl="@returnUrl">
		<select class="form-select form-select-sm" name="culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList"
		onchange="this.form.submit();"></select>
		</form>
	</div>

BulkyWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/BulkyWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/images/book.png" style="width:30px" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">@localizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">@localizer["ManageOrder"]</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">@localizer["ContentManagement"]
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">@localizer["Category"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">@localizer["Product"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">@localizer["Company"]</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">@localizer["CreateUser"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">@localizer["ManageUser"]</a>
                                    </li>
                                </ul>
                            </li>
                        }
                       
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    @await Component.InvokeAsync("ShoppingCart")
                                </a>
                            </li>

                    </ul>
                    <partial name="_Culture" />
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="mb-7">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class=" footer bg-primary text-muted">
        <div class="text-center">
            Made with <i class="bi bi-heart-fill"></i> by Farid Dibirov
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
     <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
     <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/yg0hysdvlh9iwm1xzbnl48d0qmsoadbvko404l3yojgiu7a9/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    
    <script>
        var cultureInfo = '@System.Globalization.CultureInfo.CurrentCulture.Name';
    </script>
    <script src="~/js/product.js"></script>
    <script src="~/js/company.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>